#!/usr/bin/env python3
# Regenerates FcsTriggerDefs.h (in this folder, in ../sim_to_jet/, and in
# ../StRoot/StSpinPool/StSimpleReaderMaker/) from TriggerIDs.txt.
#
# TriggerIDs.txt is one line per (name, id, first run, last run) trigger
# assignment -- the same numeric id gets reassigned to a different named
# trigger across the run period, so StSimpleReaderMaker/RecoJets/
# JetMatcher resolve a fired id to a name using (id, run number)
# together, not id alone. sim_to_jet's JetMatcher.cpp only ever sees
# flag *names* (StSimpleReaderMaker resolves them for simulated events
# via fcs_trg_base, not this id/run-range table), but needs its own copy
# of this header since it's compiled fresh in each SUMS job like
# data_to_jet/RecoJets.cpp is.
#
# Run this whenever TriggerIDs.txt changes, then rebuild StRoot
# (.sl73_x8664_gcc485) since StSimpleReaderMaker.cxx compiles against its
# copy of the generated header.
#
# Usage: python3 generate_trigger_defs.py

import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "TriggerIDs.txt")
DESTS = [
    os.path.join(HERE, "FcsTriggerDefs.h"),
    os.path.join(HERE, "..", "sim_to_jet", "FcsTriggerDefs.h"),
    os.path.join(HERE, "..", "StRoot", "StSpinPool", "StSimpleReaderMaker", "FcsTriggerDefs.h"),
]

def sanitize(name):
    return name.replace('-', '_')

def main():
    rows = []
    with open(SRC) as f:
        for line in f:
            parts = line.split()
            if len(parts) != 4:
                continue
            name, tid, r0, r1 = parts
            rows.append((name, int(tid), int(r0), int(r1)))

    from collections import defaultdict
    groups = defaultdict(set)
    for name, tid, r0, r1 in rows:
        groups[sanitize(name)].add(name)

    flagname_for_origname = {}
    for san, origs in groups.items():
        if len(origs) == 1:
            flagname_for_origname[next(iter(origs))] = san
        else:
            # Sanitized collision (e.g. "FCS15-DiELEA" and "FCS15_DiELEA"
            # both sanitize to "FCS15_DiELEA") -- these are genuinely
            # different trigger ids assigned similar-looking names, not a
            # typo, so keep them as distinct flags by suffixing the id.
            for name, tid, r0, r1 in rows:
                if name in origs:
                    flagname_for_origname[name] = f"{san}_{tid}"

    unique_flags = sorted(set(flagname_for_origname.values()))
    flag_index = {fn: i for i, fn in enumerate(unique_flags)}

    header = []
    header.append("// Auto-generated by generate_trigger_defs.py from TriggerIDs.txt.")
    header.append("// Do not hand-edit -- rerun the script instead.")
    header.append("//")
    header.append("// kTrigFlagName[i] is the branch name for flag i (one flag per")
    header.append("// distinct trigger name in TriggerIDs.txt). kTrigDef[j] = {flagIndex,")
    header.append("// triggerId, runStart, runEnd} is one (name, id, run range) row from")
    header.append("// TriggerIDs.txt; a flag is set for an event if any of its rows has a")
    header.append("// triggerId that fired and a run range covering the event's run number.")
    header.append("")
    header.append(f"static const int kNTrigFlags = {len(unique_flags)};")
    header.append("")
    header.append("static const char* const kTrigFlagName[kNTrigFlags] = {")
    for fn in unique_flags:
        header.append(f'    "{fn}",')
    header.append("};")
    header.append("")
    header.append(f"static const int kNTrigDefs = {len(rows)};")
    header.append("")
    header.append("// {flagIndex, triggerId, runStart, runEnd}")
    header.append("static const int kTrigDef[kNTrigDefs][4] = {")
    for name, tid, r0, r1 in rows:
        fi = flag_index[flagname_for_origname[name]]
        header.append(f"    {{{fi}, {tid}, {r0}, {r1}}}, // {name}")
    header.append("};")
    header.append("")

    text = "\n".join(header)
    for dest in DESTS:
        with open(dest, "w") as out:
            out.write(text)
        print(f"Wrote {dest} ({len(unique_flags)} flags, {len(rows)} definitions)")

if __name__ == "__main__":
    main()
